[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "serverlist"
version = "0.1.0"
[tool.poetry.dependencies]
flask-bootstrap = "^3.3"
flask-login = "^0.5.0"
flask-sqlalchemy = "^2.4"
flask-wtf = "^0.14.3"
mcstatus = "^3.1"
python = "^3.7"
safe = "^0.4.0"
sqlalchemy = "^1.3"
wtforms = "^2.2"
werkzeug = "^1.0"
flask = "^1.1"
Flask-MySQLdb = "^0.2.0"
elasticsearch = "^7.6"
[tool.poetry.dev-dependencies]
